version: '3.5'

services:
  automaster_postgres:
    container_name: automaster_postgres
    image: postgres
    environment:
      POSTGRES_DB: automaster
      POSTGRES_USER: automaster
      POSTGRES_PASSWORD: 1234
      PGDATA: /data/postgres
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"
    volumes:
      - postgres:/data/postgres
    restart: always

volumes:
  postgres:
