version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: automaster
      POSTGRES_USER: automaster
      POSTGRES_PASSWORD: 1234
      volumes:
        db-data:/var/lib/postgresql/data
    ports:
      - 54321:5432
    restart: always

  automaster:
    image: client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db/automaster

volumes:
  pgdata:
